services:

  _defaults:
    public: false
    autowire: true

  OxidProfessionalServices\Usercentrics\Service\Configuration\ConfigurationDaoInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Configuration\ConfigurationDao
    arguments:
      - !php/const INSTALLATION_ROOT_PATH
      - '@OxidProfessionalServices\Usercentrics\Service\Configuration\FileFormatInterface'
      - var/configuration/usercentrics.yaml

  OxidProfessionalServices\Usercentrics\Service\ScriptServiceMapperInterface:
    class: OxidProfessionalServices\Usercentrics\Service\ScriptServiceMapper

  OxidProfessionalServices\Usercentrics\Service\RendererInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Renderer
    public: true

  OxidProfessionalServices\Usercentrics\Service\Configuration\FileFormatInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Configuration\YamlFileFormat
