services:
  _defaults:
    public: false
    autowire: true
  OxidProfessionalServices\Usercentrics\Service\ConfigurationAccessInterface:
    class: OxidProfessionalServices\Usercentrics\Service\ConfigurationAccess
    arguments:
      - !php/const INSTALLATION_ROOT_PATH
      - '@OxidProfessionalServices\Usercentrics\Service\FileFormatInterface'
      - var/configuration/usercentrics.yaml

  OxidProfessionalServices\Usercentrics\Service\RepositoryInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Repository
  OxidProfessionalServices\Usercentrics\Service\RendererInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Renderer
    public: true
  OxidProfessionalServices\Usercentrics\Service\FileFormatInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Yaml
