parameters:
  oxid_professional_services.usercentrics.module_id: 'oxps_usercentrics'

services:

  _defaults:
    public: false
    autowire: true

  OxidProfessionalServices\Usercentrics\Service\Configuration\ConfigurationDaoInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Configuration\ConfigurationDao
    arguments:
      $storage: '@OxidProfessionalServices\Usercentrics\Service\Configuration\StorageInterface'

  OxidProfessionalServices\Usercentrics\Service\Configuration\StorageInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Configuration\YamlStorage
    public: true
    arguments:
      $directory: !php/const INSTALLATION_ROOT_PATH
      $fileName: /var/configuration/usercentrics.yaml

  OxidProfessionalServices\Usercentrics\Service\ScriptServiceMapperInterface:
    class: OxidProfessionalServices\Usercentrics\Service\ScriptServiceMapper

  OxidProfessionalServices\Usercentrics\Service\RendererInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Renderer
    public: true

  OxidProfessionalServices\Usercentrics\Service\IntegrationScriptInterface:
    class: OxidProfessionalServices\Usercentrics\Service\IntegrationScript
    public: true

  OxidProfessionalServices\Usercentrics\Service\ModuleSettingsInterface:
    class: OxidProfessionalServices\Usercentrics\Service\ModuleSettings
    public: true
    arguments:
      $moduleId: '%oxid_professional_services.usercentrics.module_id%'

  OxidProfessionalServices\Usercentrics\Service\Integration\IntegrationScriptBuilderInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Integration\IntegrationScriptBuilder
    public: true

  OxidProfessionalServices\Usercentrics\Service\Integration\IntegrationVersionFactoryInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Integration\IntegrationVersionFactory
