services:

  _defaults:
    public: false
    autowire: true

  OxidProfessionalServices\Usercentrics\Service\Configuration\ConfigurationDaoInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Configuration\ConfigurationDao
    arguments:
      $storage: '@OxidProfessionalServices\Usercentrics\Service\Configuration\StorageInterface'

  OxidProfessionalServices\Usercentrics\Service\Configuration\StorageInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Configuration\YamlStorage
    public: true
    arguments:
      $directory: !php/const INSTALLATION_ROOT_PATH
      $fileName: /var/configuration/usercentrics.yaml

  OxidProfessionalServices\Usercentrics\Service\ScriptServiceMapperInterface:
    class: OxidProfessionalServices\Usercentrics\Service\ScriptServiceMapper

  OxidProfessionalServices\Usercentrics\Service\RendererInterface:
    class: OxidProfessionalServices\Usercentrics\Service\Renderer
    public: true
